apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-deployment
spec:
  selector:
    matchLabels:
      app: k8s-test
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-test
    spec:
      containers:
      - name: k8s-test
        image: giefferre/k8s-test:dev
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          timeoutSeconds: 10
        ports:
        - containerPort: 5000